<div class="container vh-100 d-flex justify-content-center align-items-center">
    <div class="card shadow-lg p-4" style="max-width: 400px; width: 100%;">
        <div class="card-body">
            <h3 class="text-center mb-4">Login</h3>
            <form action="/login" method="POST">
                <div class="mb-3">
                    <label for="email" class="form-label">Email:</label>
                    <input type="email" name="email" id="email" class="form-control" required placeholder="Digite seu email">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Senha:</label>
                    <input type="password" name="password" id="password" class="form-control" required placeholder="Digite sua senha">
                </div>
                <button type="submit" class="btn btn-primary w-100">Entrar</button>
                <p>admin@petstore.com</p>
                <p>adminpassword</p>
                <p>user@petstore.com</p>
                <p>userpassword</p>
            </form>
        </div>
        <a href="/" class="btn btn-secondary"><i class="bi bi-arrow-left"></i> Voltar para Página Inicial</a>
    </div>
</div>
