<div class="container mt-5">
    <h1 class="text-center mb-4">Criar Nova Categoria</h1>
    <div class="d-flex justify-content-start mb-3">
        <a href="/admin/categories" class="btn btn-secondary"><i class="bi bi-arrow-left"></i> Voltar</a>
    </div>
    <form action="/admin/categories/store" method="POST">
        <div class="mb-3">
            <label for="name" class="form-label">Nome da Categoria</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary"><i class="bi bi-check-circle"></i> Salvar</button>
    </form>
</div>